# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formClassificacaoFiscal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication, QWidget, QFileDialog, QTableWidget, QTableWidgetItem

# lib conexão MySQL
import mysql.connector

### Import das Variaveis Controle ###
import variaveisDeControles

### Variáveis de conexão com o banco de dados ###
host = variaveisDeControles.host
user = variaveisDeControles.user
password = variaveisDeControles.password
database = variaveisDeControles.database

# Imports libs gerais
from datetime import datetime
import subprocess
import pandas as pd
import funcoesAuxiliares
from decimal import Decimal


class Ui_formClassificacaoFiscal(object):
    def setupUi(self, formClassificacaoFiscal):
        formClassificacaoFiscal.setObjectName("formClassificacaoFiscal")
        formClassificacaoFiscal.resize(811, 531)
        self.txt_pesquisarPor = QtWidgets.QLabel(formClassificacaoFiscal)
        self.txt_pesquisarPor.setGeometry(QtCore.QRect(30, 100, 91, 20))
        self.txt_pesquisarPor.setObjectName("txt_pesquisarPor")
        self.bt_sair = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_sair.setGeometry(QtCore.QRect(720, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_sair.setFont(font)
        self.bt_sair.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_sair.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/iconSair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_sair.setIcon(icon)
        self.bt_sair.setIconSize(QtCore.QSize(80, 80))
        self.bt_sair.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_sair.setObjectName("bt_sair")
        self.bt_incluir = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_incluir.setGeometry(QtCore.QRect(0, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_incluir.setFont(font)
        self.bt_incluir.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_incluir.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/iconAdicionar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_incluir.setIcon(icon1)
        self.bt_incluir.setIconSize(QtCore.QSize(80, 80))
        self.bt_incluir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_incluir.setObjectName("bt_incluir")
        self.bt_pesquisar = QtWidgets.QPushButton(formClassificacaoFiscal)
        self.bt_pesquisar.setGeometry(QtCore.QRect(650, 100, 21, 23))
        self.bt_pesquisar.setStyleSheet("")
        self.bt_pesquisar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/iconPesquisar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pesquisar.setIcon(icon2)
        self.bt_pesquisar.setObjectName("bt_pesquisar")
        self.tb_classificacaoFiscal = QtWidgets.QTableWidget(formClassificacaoFiscal)
        self.tb_classificacaoFiscal.setEnabled(True)
        self.tb_classificacaoFiscal.setGeometry(QtCore.QRect(0, 151, 811, 381))
        self.tb_classificacaoFiscal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tb_classificacaoFiscal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tb_classificacaoFiscal.setAutoScroll(True)
        self.tb_classificacaoFiscal.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_classificacaoFiscal.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tb_classificacaoFiscal.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tb_classificacaoFiscal.setObjectName("tb_classificacaoFiscal")
        self.tb_classificacaoFiscal.setColumnCount(8)
        self.tb_classificacaoFiscal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("ID")
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_classificacaoFiscal.setHorizontalHeaderItem(7, item)
        self.tb_classificacaoFiscal.horizontalHeader().setVisible(True)
        self.tb_classificacaoFiscal.verticalHeader().setVisible(False)
        self.lb_pesquisar = QtWidgets.QLineEdit(formClassificacaoFiscal)
        self.lb_pesquisar.setGeometry(QtCore.QRect(330, 100, 301, 20))
        self.lb_pesquisar.setObjectName("lb_pesquisar")
        self.bt_pesquisarGeral = QtWidgets.QPushButton(formClassificacaoFiscal)
        self.bt_pesquisarGeral.setGeometry(QtCore.QRect(680, 100, 21, 23))
        self.bt_pesquisarGeral.setStyleSheet("")
        self.bt_pesquisarGeral.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/iconFiltro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pesquisarGeral.setIcon(icon3)
        self.bt_pesquisarGeral.setObjectName("bt_pesquisarGeral")
        self.bt_alterar = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_alterar.setGeometry(QtCore.QRect(90, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_alterar.setFont(font)
        self.bt_alterar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_alterar.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/iconAlterar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_alterar.setIcon(icon4)
        self.bt_alterar.setIconSize(QtCore.QSize(80, 80))
        self.bt_alterar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_alterar.setObjectName("bt_alterar")
        self.bt_consultar = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_consultar.setGeometry(QtCore.QRect(180, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_consultar.setFont(font)
        self.bt_consultar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_consultar.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/iconConsultar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_consultar.setIcon(icon5)
        self.bt_consultar.setIconSize(QtCore.QSize(80, 80))
        self.bt_consultar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_consultar.setObjectName("bt_consultar")
        self.bt_excluir = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_excluir.setGeometry(QtCore.QRect(270, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_excluir.setFont(font)
        self.bt_excluir.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_excluir.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/iconCancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_excluir.setIcon(icon6)
        self.bt_excluir.setIconSize(QtCore.QSize(80, 80))
        self.bt_excluir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_excluir.setObjectName("bt_excluir")
        self.bt_inutilizado1 = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_inutilizado1.setGeometry(QtCore.QRect(360, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_inutilizado1.setFont(font)
        self.bt_inutilizado1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_inutilizado1.setStyleSheet("")
        self.bt_inutilizado1.setText("")
        self.bt_inutilizado1.setIconSize(QtCore.QSize(80, 80))
        self.bt_inutilizado1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_inutilizado1.setObjectName("bt_inutilizado1")
        self.bt_inutilizado2 = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_inutilizado2.setGeometry(QtCore.QRect(450, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_inutilizado2.setFont(font)
        self.bt_inutilizado2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_inutilizado2.setStyleSheet("")
        self.bt_inutilizado2.setText("")
        self.bt_inutilizado2.setIconSize(QtCore.QSize(80, 80))
        self.bt_inutilizado2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_inutilizado2.setObjectName("bt_inutilizado2")
        self.bt_excel = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_excel.setGeometry(QtCore.QRect(540, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_excel.setFont(font)
        self.bt_excel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_excel.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/iconExcel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_excel.setIcon(icon7)
        self.bt_excel.setIconSize(QtCore.QSize(80, 80))
        self.bt_excel.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_excel.setObjectName("bt_excel")
        self.bt_imprimir = QtWidgets.QToolButton(formClassificacaoFiscal)
        self.bt_imprimir.setGeometry(QtCore.QRect(630, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_imprimir.setFont(font)
        self.bt_imprimir.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_imprimir.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/iconVenda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_imprimir.setIcon(icon8)
        self.bt_imprimir.setIconSize(QtCore.QSize(80, 80))
        self.bt_imprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_imprimir.setObjectName("bt_imprimir")
        self.txt_digiteAqui = QtWidgets.QLabel(formClassificacaoFiscal)
        self.txt_digiteAqui.setGeometry(QtCore.QRect(260, 100, 71, 20))
        self.txt_digiteAqui.setObjectName("txt_digiteAqui")
        self.cb_pesquisarPor = QtWidgets.QComboBox(formClassificacaoFiscal)
        self.cb_pesquisarPor.setGeometry(QtCore.QRect(130, 100, 111, 22))
        self.cb_pesquisarPor.setObjectName("cb_pesquisarPor")
        self.cb_pesquisarPor.addItem("")
        self.cb_pesquisarPor.addItem("")
        self.frameDadosClassificacaoFiscal = QtWidgets.QFrame(formClassificacaoFiscal)
        self.frameDadosClassificacaoFiscal.setGeometry(QtCore.QRect(220, 220, 361, 211))
        self.frameDadosClassificacaoFiscal.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.frameDadosClassificacaoFiscal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDadosClassificacaoFiscal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDadosClassificacaoFiscal.setObjectName("frameDadosClassificacaoFiscal")
        self.gb_dados = QtWidgets.QGroupBox(self.frameDadosClassificacaoFiscal)
        self.gb_dados.setGeometry(QtCore.QRect(10, 0, 341, 131))
        self.gb_dados.setObjectName("gb_dados")
        self.txt_descricao = QtWidgets.QLabel(self.gb_dados)
        self.txt_descricao.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.txt_descricao.setObjectName("txt_descricao")
        self.lb_descricao = QtWidgets.QLineEdit(self.gb_dados)
        self.lb_descricao.setGeometry(QtCore.QRect(30, 90, 291, 20))
        self.lb_descricao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_descricao.setText("")
        self.lb_descricao.setObjectName("lb_descricao")
        self.lb_codigo = QtWidgets.QLineEdit(self.gb_dados)
        self.lb_codigo.setGeometry(QtCore.QRect(30, 40, 101, 20))
        self.lb_codigo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_codigo.setText("")
        self.lb_codigo.setObjectName("lb_codigo")
        self.txt_nivel = QtWidgets.QLabel(self.gb_dados)
        self.txt_nivel.setGeometry(QtCore.QRect(140, 20, 41, 16))
        self.txt_nivel.setObjectName("txt_nivel")
        self.txt_sinal = QtWidgets.QLabel(self.gb_dados)
        self.txt_sinal.setGeometry(QtCore.QRect(240, 20, 41, 16))
        self.txt_sinal.setObjectName("txt_sinal")
        self.txt_conta = QtWidgets.QLabel(self.gb_dados)
        self.txt_conta.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.txt_conta.setObjectName("txt_conta")
        self.sb_iva = QtWidgets.QDoubleSpinBox(self.gb_dados)
        self.sb_iva.setGeometry(QtCore.QRect(140, 40, 91, 22))
        self.sb_iva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sb_iva.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_iva.setMaximum(100.0)
        self.sb_iva.setObjectName("sb_iva")
        self.sb_ipi = QtWidgets.QDoubleSpinBox(self.gb_dados)
        self.sb_ipi.setGeometry(QtCore.QRect(240, 40, 91, 22))
        self.sb_ipi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sb_ipi.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_ipi.setMaximum(100.0)
        self.sb_ipi.setObjectName("sb_ipi")
        self.bt_cancelar = QtWidgets.QToolButton(self.frameDadosClassificacaoFiscal)
        self.bt_cancelar.setGeometry(QtCore.QRect(30, 140, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_cancelar.setFont(font)
        self.bt_cancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_cancelar.setStyleSheet("")
        self.bt_cancelar.setIcon(icon6)
        self.bt_cancelar.setIconSize(QtCore.QSize(48, 48))
        self.bt_cancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.bt_alterarCadastro = QtWidgets.QToolButton(self.frameDadosClassificacaoFiscal)
        self.bt_alterarCadastro.setGeometry(QtCore.QRect(200, 140, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_alterarCadastro.setFont(font)
        self.bt_alterarCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_alterarCadastro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_alterarCadastro.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/iconCancelarNFe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_alterarCadastro.setIcon(icon9)
        self.bt_alterarCadastro.setIconSize(QtCore.QSize(40, 48))
        self.bt_alterarCadastro.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_alterarCadastro.setObjectName("bt_alterarCadastro")
        self.bt_confirmar = QtWidgets.QToolButton(self.frameDadosClassificacaoFiscal)
        self.bt_confirmar.setGeometry(QtCore.QRect(200, 140, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_confirmar.setFont(font)
        self.bt_confirmar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_confirmar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_confirmar.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/iconConfirmar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_confirmar.setIcon(icon10)
        self.bt_confirmar.setIconSize(QtCore.QSize(40, 48))
        self.bt_confirmar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_confirmar.setObjectName("bt_confirmar")

        self.retranslateUi(formClassificacaoFiscal)
        self.bt_incluir.clicked.connect(self.frameDadosClassificacaoFiscal.show) # type: ignore
        self.bt_incluir.clicked.connect(self.bt_alterarCadastro.hide) # type: ignore
        self.bt_alterar.clicked.connect(self.frameDadosClassificacaoFiscal.show) # type: ignore
        self.bt_alterar.clicked.connect(self.bt_confirmar.hide) # type: ignore
        self.bt_consultar.clicked.connect(self.frameDadosClassificacaoFiscal.show) # type: ignore
        self.bt_consultar.clicked.connect(self.bt_alterarCadastro.hide) # type: ignore
        self.bt_consultar.clicked.connect(self.bt_confirmar.hide) # type: ignore
        self.bt_cancelar.clicked.connect(self.frameDadosClassificacaoFiscal.hide) # type: ignore
        self.bt_confirmar.clicked.connect(self.frameDadosClassificacaoFiscal.hide) # type: ignore
        self.bt_alterarCadastro.clicked.connect(self.frameDadosClassificacaoFiscal.hide) # type: ignore
        self.bt_alterar.clicked.connect(self.bt_alterarCadastro.show) # type: ignore
        self.bt_incluir.clicked.connect(self.bt_confirmar.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(formClassificacaoFiscal)
        formClassificacaoFiscal.setTabOrder(self.lb_codigo, self.sb_iva)
        formClassificacaoFiscal.setTabOrder(self.sb_iva, self.sb_ipi)
        formClassificacaoFiscal.setTabOrder(self.sb_ipi, self.lb_descricao)
        formClassificacaoFiscal.setTabOrder(self.lb_descricao, self.cb_pesquisarPor)
        formClassificacaoFiscal.setTabOrder(self.cb_pesquisarPor, self.lb_pesquisar)
        formClassificacaoFiscal.setTabOrder(self.lb_pesquisar, self.bt_pesquisar)
        formClassificacaoFiscal.setTabOrder(self.bt_pesquisar, self.bt_pesquisarGeral)
        formClassificacaoFiscal.setTabOrder(self.bt_pesquisarGeral, self.tb_classificacaoFiscal)

    def retranslateUi(self, formClassificacaoFiscal):
        _translate = QtCore.QCoreApplication.translate
        formClassificacaoFiscal.setWindowTitle(_translate("formClassificacaoFiscal", "Classificação Fiscal"))
        self.txt_pesquisarPor.setText(_translate("formClassificacaoFiscal", "Pesquisar por:"))
        self.bt_sair.setText(_translate("formClassificacaoFiscal", "Sair"))
        self.bt_incluir.setText(_translate("formClassificacaoFiscal", "Incluir"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(1)
        item.setText(_translate("formClassificacaoFiscal", "Código"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(2)
        item.setText(_translate("formClassificacaoFiscal", "Descrição"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(3)
        item.setText(_translate("formClassificacaoFiscal", "IVA"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(4)
        item.setText(_translate("formClassificacaoFiscal", "IPI"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(5)
        item.setText(_translate("formClassificacaoFiscal", "usuario"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(6)
        item.setText(_translate("formClassificacaoFiscal", "Auditoria"))
        item = self.tb_classificacaoFiscal.horizontalHeaderItem(7)
        item.setText(_translate("formClassificacaoFiscal", "Ativo"))
        self.bt_alterar.setText(_translate("formClassificacaoFiscal", "Alterar"))
        self.bt_consultar.setText(_translate("formClassificacaoFiscal", "Consultar"))
        self.bt_excluir.setText(_translate("formClassificacaoFiscal", "Excluir"))
        self.bt_excel.setText(_translate("formClassificacaoFiscal", "Excel"))
        self.bt_imprimir.setText(_translate("formClassificacaoFiscal", "Imprimir"))
        self.txt_digiteAqui.setText(_translate("formClassificacaoFiscal", "Digite Aqui:"))
        self.cb_pesquisarPor.setItemText(0, _translate("formClassificacaoFiscal", "Código"))
        self.cb_pesquisarPor.setItemText(1, _translate("formClassificacaoFiscal", "Descrição"))
        self.gb_dados.setTitle(_translate("formClassificacaoFiscal", "Dados"))
        self.txt_descricao.setText(_translate("formClassificacaoFiscal", "Descrição:"))
        self.txt_nivel.setText(_translate("formClassificacaoFiscal", "IVA:"))
        self.txt_sinal.setText(_translate("formClassificacaoFiscal", "IPI:"))
        self.txt_conta.setText(_translate("formClassificacaoFiscal", "Código:"))
        self.bt_cancelar.setText(_translate("formClassificacaoFiscal", "Cancelar"))
        self.bt_alterarCadastro.setText(_translate("formClassificacaoFiscal", "Alterar"))
        self.bt_confirmar.setText(_translate("formClassificacaoFiscal", "Confirmar"))
        
        
        
        # Esconde funções da tela
        self.frameDadosClassificacaoFiscal.hide()

        # Conexões dos botões
        self.bt_confirmar.clicked.connect(self.cadastrarClassificacaoFiscal) # Cadastra dados no Banco de Dados
        self.bt_pesquisar.clicked.connect(self.consultar) # Consulta baseado na pesquisa do usuário
        self.bt_pesquisarGeral.clicked.connect(self.consultaGeral) # Consulta geral tabela ClassificacaoFiscal
        self.bt_excluir.clicked.connect(self.excluirClassificacaoFiscal) # Exclui o ClassificacaoFiscal conforme linha selecionada
        self.bt_alterar.clicked.connect(self.abrirDadosClassificacaoFiscal) # Consulta os dados do ClassificacaoFiscal trazendo nas labels
        self.bt_alterarCadastro.clicked.connect(self.alterarClassificacaoFiscal) # Altera dados do ClassificacaoFiscal
        self.bt_consultar.clicked.connect(self.consultarClassificacaoFiscal) # Consulta os dados do ClassificacaoFiscal
        self.bt_cancelar.clicked.connect(self.cancelarOperacao) # Cancela a operação do usuário
        self.bt_sair.clicked.connect(formClassificacaoFiscal.close) # Fecha a tela


    # Funções Sistema
    # Cancela operação do usuário
    def cancelarOperacao(self):
        # Destravar as labels
        self.gb_dados.setEnabled(True)
        # Limpar as labels
        self.lb_codigo.clear()
        self.lb_descricao.clear()
        self.sb_ipi.setValue(0)
        self.sb_iva.setValue(0)
    # Consulta os dados do cliente
    def consultarClassificacaoFiscal(self):
        #self.lb_razaoSocial.setEnabled(False) # Apenas para terem como referência que pode ser setado por label também
        self.gb_dados.setEnabled(False)
        # Verificar qual cliente o usário quer consultar
        linha = self.tb_classificacaoFiscal.currentRow()
        idClassificacaoFiscalLinha = self.tb_classificacaoFiscal.item(linha, 0).text()
        # Tenta realizar a conexão com o BD e executar a Query
        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()
            consultaUsuario = self.lb_pesquisar.text()
            consultaSQL = "SELECT * FROM classificacaofiscal WHERE idclassificacaoFiscal = " + idClassificacaoFiscalLinha + " ORDER by codigo"
            mycursor.execute(consultaSQL)
            myresult = mycursor.fetchall()
            df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
            # Seta labels da tela em variáveis
            self.lb_codigo.setText(df_classificacaoFiscal.loc[0][1])
            self.lb_descricao.setText(df_classificacaoFiscal.loc[0][2])
            self.sb_iva.setValue(float(df_classificacaoFiscal.loc[0][3]))
            self.sb_ipi.setValue(float(df_classificacaoFiscal.loc[0][4]))
            mycursor.close()
        except:
            self.all_data = 0
            print(consultaSQL)
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Error")
            msg.setInformativeText('Erro ao consultar a classificação fiscal, favor contactar o administrador do sistema!')
            msg.setWindowTitle("Error")
            msg.exec_()
            pass
    # Confirma a alteração dos dados da classificacaofiscal no Banco de Dados
    def alterarClassificacaoFiscal(self):
        # Verifica qual idclassificacaoFiscal está selecionado e altera os dados do cliente
        linha = self.tb_classificacaoFiscal.currentRow()
        idClassificacaoFiscalLinha = self.tb_classificacaoFiscal.item(linha, 0).text()
        # Seta labels da tela em variáveis
        codigo = self.lb_codigo.text()
        descricao = self.lb_descricao.text()
        iva = self.sb_iva.value() 
        ipi = self.sb_iva.value() 
        iva = funcoesAuxiliares.valorPTBRtoUS(iva)
        ipi = funcoesAuxiliares.valorPTBRtoUS(ipi)
        usuarioCadastro = 1
        dataHoje = datetime.today().strftime('%Y-%m-%d %H:%M:%S')
        serialUniqPC = subprocess.check_output('wmic bios get serialnumber').decode("utf-8") 
        auditoria = str(dataHoje) + ' ' + str(serialUniqPC[27:49])
        ativo = 'S'
        # Confere se elas foram preenchidas ou não, se não coloca "None"
        if codigo == '':
            codigo = None
        if descricao == '':
            descricao = None
        if iva == '':
            iva = None
        if ipi == '':
            ipi = None
        # Tenta realizar a conexão com o BD e executar a Query
        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()
            sql = "UPDATE classificacaofiscal SET codigo = %s, descricao = %s, iva = %s, ipi = %s,  usuarioCadastro = %s, auditoria = %s, ativo = %s WHERE idclassificacaoFiscal = %s"
            val = (codigo, descricao, iva, ipi, usuarioCadastro, auditoria, ativo, idClassificacaoFiscalLinha)
            mycursor.execute(sql, val)
            # Make sure data is committed to the database
            mydb.commit()
            print(mycursor.rowcount, "record(s) affected")
            # Limpar as labels
            self.lb_codigo.clear()
            self.lb_descricao.clear()
            self.sb_ipi.setValue(0)
            self.sb_iva.setValue(0)
            # Atualiza a tabela classificacaoFiscal
            mycursor.execute("SELECT * FROM classificacaofiscal WHERE ativo = 'S' ORDER by codigo")
            myresult = mycursor.fetchall()
            df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
            self.all_data = df_classificacaoFiscal
            # Carrega o arquivo na tabela tb_classificacaoFiscal#
            numRows = len(self.all_data.index)
            self.tb_classificacaoFiscal.setColumnCount(len(self.all_data.columns))
            self.tb_classificacaoFiscal.setRowCount(numRows)
            self.tb_classificacaoFiscal.setHorizontalHeaderLabels(self.all_data.columns)
            for i in range(numRows):
                for j in range(len(self.all_data.columns)):
                    self.tb_classificacaoFiscal.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))
            self.tb_classificacaoFiscal.resizeColumnsToContents()
            self.tb_classificacaoFiscal.resizeRowsToContents()
            # Mensagem de alteração de dados realizada
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Aviso")
            aviso = mycursor.rowcount, "Classificacao Fiscal alterado"
            msg.setInformativeText(str(aviso))
            msg.setWindowTitle("Informação")
            msg.exec_()
        except:
            print(sql)
            print(val)
            print('Erro na alteração dos dados')
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Erro SQL")
            msg.setInformativeText('Favor contactar o administrador do sistema!')
            msg.setWindowTitle("Erro")
            msg.exec_()
    # Carrega dados da ClassificacaoFiscal nas labels
    def abrirDadosClassificacaoFiscal(self):
        linha = self.tb_classificacaoFiscal.currentRow()
        idClassificacaoFiscalLinha = self.tb_classificacaoFiscal.item(linha, 0).text()
        # Tenta realizar a conexão com o BD e executar a Query
        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()
            consultaSQL = "SELECT * FROM classificacaofiscal WHERE idclassificacaoFiscal = " + idClassificacaoFiscalLinha
            mycursor.execute(consultaSQL)
            myresult = mycursor.fetchall()
            df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
            # Seta labels da tela em variáveis
            self.lb_codigo.setText(df_classificacaoFiscal.loc[0][1])
            self.lb_descricao.setText(df_classificacaoFiscal.loc[0][2])
            self.sb_iva.setValue(float(df_classificacaoFiscal.loc[0][3]))
            self.sb_ipi.setValue(float(df_classificacaoFiscal.loc[0][4]))
        except:
            self.all_data = 0
            print(consultaSQL)
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Error")
            msg.setInformativeText('Favor contactar o administrador do sistema!')
            msg.setWindowTitle("Error")
            msg.exec_()
            pass
    # Cadastrar dados na tabela Cliente
    def cadastrarClassificacaoFiscal(self):
        # Seta labels da tela em variáveis
        codigo = self.lb_codigo.text()
        descricao = self.lb_descricao.text()
        iva = self.sb_iva.value() 
        ipi = self.sb_iva.value() 
        iva = funcoesAuxiliares.valorPTBRtoUS(iva)
        ipi = funcoesAuxiliares.valorPTBRtoUS(ipi)
        usuarioCadastro = 1
        dataHoje = datetime.today().strftime('%Y-%m-%d %H:%M:%S')
        serialUniqPC = subprocess.check_output('wmic bios get serialnumber').decode("utf-8") 
        auditoria = str(dataHoje) + ' ' + str(serialUniqPC[27:49])
        ativo = 'S'
        # Confere se elas foram preenchidas ou não, se não coloca "None"
        if codigo == '':
            codigo = None
        if descricao == '':
            descricao = None
        if iva == '':
            iva = None
        if ipi == '':
            ipi = None
        # Tenta realizar a conexão com o BD e executar a Query
        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()
            sql = "INSERT INTO classificacaofiscal (codigo, descricao, iva, ipi, usuarioCadastro, auditoria, ativo) VALUES (%s, %s, %s, %s, %s, %s, %s)"
            val = (codigo, descricao, iva, ipi, usuarioCadastro, auditoria, ativo)
            mycursor.execute(sql, val)
            # Make sure data is committed to the database
            mydb.commit()
            # Limpa as labels da tela
            self.lb_codigo.clear()
            self.lb_descricao.clear()
            self.sb_ipi.setValue(0)
            self.sb_iva.setValue(0)
            # Atualiza a tabela classificacaoFiscal
            mycursor.execute("SELECT * FROM classificacaofiscal WHERE ativo = 'S' ORDER by codigo")
            myresult = mycursor.fetchall()
            df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
            self.all_data = df_classificacaoFiscal
            # Carrega o arquivo na tabela tb_classificacaoFiscal#
            numRows = len(self.all_data.index)
            self.tb_classificacaoFiscal.setColumnCount(len(self.all_data.columns))
            self.tb_classificacaoFiscal.setRowCount(numRows)
            self.tb_classificacaoFiscal.setHorizontalHeaderLabels(self.all_data.columns)
            for i in range(numRows):
                for j in range(len(self.all_data.columns)):
                    self.tb_classificacaoFiscal.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))
            self.tb_classificacaoFiscal.resizeColumnsToContents()
            self.tb_classificacaoFiscal.resizeRowsToContents()
            # Mensagem de Inclusão de dados realizada
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Aviso")
            msg.setInformativeText('Dados incluídos no sistema!')
            msg.setWindowTitle("Informação")
            msg.exec_()
        except:
            print('Erro na inclusão dos dados')
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Erro SQL")
            msg.setInformativeText('Favor contactar o administrador do sistema!')
            msg.setWindowTitle("Erro")
            msg.exec_()
            # disconnecting from DB
            mycursor.close()
            mydb.close()
    # Consulta baseado na pesquisa do usuário na tabea cliente do BD
    def consultar(self):
        # Tenta realizar a conexão com o BD e executar a Query
        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()
            consultaUsuario = self.lb_pesquisar.text()
            consultaSQL = "SELECT * FROM classificacaofiscal WHERE codigo LIKE '" + consultaUsuario + "%' AND ativo = 'S' ORDER by codigo"
            print(consultaSQL)
            mycursor.execute(consultaSQL)
            myresult = mycursor.fetchall()
            df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
            self.all_data = df_classificacaoFiscal
            # Carrega o arquivo na tabela tb_classificacaoFiscal#
            numRows = len(self.all_data.index)
            self.tb_classificacaoFiscal.setColumnCount(len(self.all_data.columns))
            self.tb_classificacaoFiscal.setRowCount(numRows)
            self.tb_classificacaoFiscal.setHorizontalHeaderLabels(self.all_data.columns)
            for i in range(numRows):
                for j in range(len(self.all_data.columns)):
                    self.tb_classificacaoFiscal.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))
            self.tb_classificacaoFiscal.resizeColumnsToContents()
            self.tb_classificacaoFiscal.resizeRowsToContents()
            mycursor.close()
        except:
            self.all_data = 0
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Error")
            msg.setInformativeText('Favor contactar o administrador do sistema!')
            msg.setWindowTitle("Error")
            msg.exec_()
            pass
    # Exclui do cliente conforme linha selecionada
    def excluirClassificacaoFiscal(self):
        reply = QMessageBox()
        reply.setIcon(QMessageBox.Critical)
        reply.setWindowTitle("Aviso")
        reply.setText("Deseja realmente excluir os dados?")
        reply.setStandardButtons(QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)
        ret = reply.exec()
        if ret == QMessageBox.StandardButton.Yes:
            linha = self.tb_classificacaoFiscal.currentRow()
            idClassificacaoFiscalLinha = self.tb_classificacaoFiscal.item(linha, 0).text()
            # Tenta realizar a conexão com o BD e executar a Query
            try:
                mydb = mysql.connector.connect(
                    host = host,
                    user = user,
                    password = password,
                    database = database
                )
                mycursor = mydb.cursor()
                sql = "UPDATE classificacaofiscal SET ativo = %s WHERE idclassificacaoFiscal = %s"
                val = ('N', idClassificacaoFiscalLinha)
                mycursor.execute(sql, val)
                # Make sure data is committed to the database
                mydb.commit()
                print(mycursor.rowcount, "record(s) affected")
                # Atualiza a tabela classificacaoFiscal
                mycursor.execute("SELECT * FROM classificacaofiscal WHERE ativo = 'S' ORDER by codigo")
                myresult = mycursor.fetchall()
                df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
                self.all_data = df_classificacaoFiscal
                # Carrega o arquivo na tabela tb_classificacaoFiscal#
                numRows = len(self.all_data.index)
                self.tb_classificacaoFiscal.setColumnCount(len(self.all_data.columns))
                self.tb_classificacaoFiscal.setRowCount(numRows)
                self.tb_classificacaoFiscal.setHorizontalHeaderLabels(self.all_data.columns)
                for i in range(numRows):
                    for j in range(len(self.all_data.columns)):
                        self.tb_classificacaoFiscal.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))
                self.tb_classificacaoFiscal.resizeColumnsToContents()
                self.tb_classificacaoFiscal.resizeRowsToContents()
            except:
                print(sql)
                print(val)
                print('Erro na exclusão dos dados')
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Erro SQL")
                msg.setInformativeText('Favor contactar o administrador do sistema!')
                msg.setWindowTitle("Erro")
                msg.exec_()
                # disconnecting from DB
                mycursor.close()
                mydb.close()
    # Consulta Geral a tabela classificacaofiscal do BD
    def consultaGeral(self):
        # Tenta realizar a conexão com o BD e executar a Query
        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM classificacaofiscal WHERE ativo = 'S' ORDER by codigo")
            myresult = mycursor.fetchall()
            df_classificacaoFiscal = pd.DataFrame(myresult, columns = ['idclassificacaoFiscal', 'codigo', 'descricao', 'iva', 'ipi', 'usuarioCadastro', 'auditoria', 'ativo'])
            self.all_data = df_classificacaoFiscal
            # Carrega o arquivo na tabela tb_classificacaoFiscal#
            numRows = len(self.all_data.index)
            self.tb_classificacaoFiscal.setColumnCount(len(self.all_data.columns))
            self.tb_classificacaoFiscal.setRowCount(numRows)
            self.tb_classificacaoFiscal.setHorizontalHeaderLabels(self.all_data.columns)
            for i in range(numRows):
                for j in range(len(self.all_data.columns)):
                    self.tb_classificacaoFiscal.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))
            self.tb_classificacaoFiscal.resizeColumnsToContents()
            self.tb_classificacaoFiscal.resizeRowsToContents()
            mycursor.close()
        except:
            self.all_data = 0
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Error")
            msg.setInformativeText('Favor contactar o administrador do sistema!')
            msg.setWindowTitle("Error")
            msg.exec_()
            pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formClassificacaoFiscal = QtWidgets.QWidget()
    ui = Ui_formClassificacaoFiscal()
    ui.setupUi(formClassificacaoFiscal)
    formClassificacaoFiscal.show()
    sys.exit(app.exec_())
