# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QTableWidgetItem


#Todo: ferramentos externas

import mysql.connector
import pandas as pd
from datetime import datetime
import subprocess




#Todo: importações de telas
import variaveisDeControles

###Todo: variaveis com a conexão do banco de dados.

host = variaveisDeControles.host
user = variaveisDeControles.user
password = variaveisDeControles.password
database = variaveisDeControles.database


class Ui_formCliente(object):
    def __init__(self):
        self.all_data = None

    def setupUi(self, formCliente):
        formCliente.setObjectName("formCliente")
        formCliente.resize(813, 703)
        self.txt_nomeCliente = QtWidgets.QLabel(formCliente)
        self.txt_nomeCliente.setGeometry(QtCore.QRect(60, 100, 111, 20))
        self.txt_nomeCliente.setObjectName("txt_nomeCliente")
        self.bt_sair = QtWidgets.QToolButton(formCliente)
        self.bt_sair.setGeometry(QtCore.QRect(720, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_sair.setFont(font)
        self.bt_sair.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_sair.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/iconSair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_sair.setIcon(icon)
        self.bt_sair.setIconSize(QtCore.QSize(80, 80))
        self.bt_sair.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_sair.setObjectName("bt_sair")
        self.bt_incluir = QtWidgets.QToolButton(formCliente)
        self.bt_incluir.setGeometry(QtCore.QRect(0, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_incluir.setFont(font)
        self.bt_incluir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_incluir.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/iconAdicionar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_incluir.setIcon(icon1)
        self.bt_incluir.setIconSize(QtCore.QSize(80, 80))
        self.bt_incluir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_incluir.setObjectName("bt_incluir")
        self.bt_pesquisar = QtWidgets.QPushButton(formCliente)
        self.bt_pesquisar.setGeometry(QtCore.QRect(640, 100, 21, 23))
        self.bt_pesquisar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_pesquisar.setStyleSheet("")
        self.bt_pesquisar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/iconPesquisar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pesquisar.setIcon(icon2)
        self.bt_pesquisar.setObjectName("bt_pesquisar")
        self.tb_cliente = QtWidgets.QTableWidget(formCliente)
        self.tb_cliente.setEnabled(True)
        self.tb_cliente.setGeometry(QtCore.QRect(0, 151, 811, 551))
        self.tb_cliente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tb_cliente.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tb_cliente.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tb_cliente.setAutoScroll(True)
        self.tb_cliente.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_cliente.setTextElideMode(QtCore.Qt.ElideRight)
        self.tb_cliente.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tb_cliente.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tb_cliente.setObjectName("tb_cliente")
        self.tb_cliente.setColumnCount(18)
        self.tb_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("ID")
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tb_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_cliente.setHorizontalHeaderItem(17, item)
        self.tb_cliente.horizontalHeader().setVisible(True)
        self.tb_cliente.verticalHeader().setVisible(False)
        self.lb_nomeCliente = QtWidgets.QLineEdit(formCliente)
        self.lb_nomeCliente.setGeometry(QtCore.QRect(160, 100, 461, 20))
        self.lb_nomeCliente.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lb_nomeCliente.setObjectName("lb_nomeCliente")
        self.bt_pesquisarGeral = QtWidgets.QPushButton(formCliente)
        self.bt_pesquisarGeral.setGeometry(QtCore.QRect(670, 100, 21, 23))
        self.bt_pesquisarGeral.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_pesquisarGeral.setStyleSheet("")
        self.bt_pesquisarGeral.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/iconFiltro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pesquisarGeral.setIcon(icon3)
        self.bt_pesquisarGeral.setObjectName("bt_pesquisarGeral")
        self.bt_alterar = QtWidgets.QToolButton(formCliente)
        self.bt_alterar.setGeometry(QtCore.QRect(90, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_alterar.setFont(font)
        self.bt_alterar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_alterar.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/iconAlterar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_alterar.setIcon(icon4)
        self.bt_alterar.setIconSize(QtCore.QSize(80, 80))
        self.bt_alterar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_alterar.setObjectName("bt_alterar")
        self.bt_consultar = QtWidgets.QToolButton(formCliente)
        self.bt_consultar.setGeometry(QtCore.QRect(180, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_consultar.setFont(font)
        self.bt_consultar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_consultar.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/iconConsultar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_consultar.setIcon(icon5)
        self.bt_consultar.setIconSize(QtCore.QSize(80, 80))
        self.bt_consultar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_consultar.setObjectName("bt_consultar")
        self.bt_excluir = QtWidgets.QToolButton(formCliente)
        self.bt_excluir.setGeometry(QtCore.QRect(270, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_excluir.setFont(font)
        self.bt_excluir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_excluir.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/iconCancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_excluir.setIcon(icon6)
        self.bt_excluir.setIconSize(QtCore.QSize(80, 80))
        self.bt_excluir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_excluir.setObjectName("bt_excluir")
        self.frameDadosCliente = QtWidgets.QFrame(formCliente)
        self.frameDadosCliente.setGeometry(QtCore.QRect(130, 180, 541, 461))
        self.frameDadosCliente.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.frameDadosCliente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDadosCliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDadosCliente.setObjectName("frameDadosCliente")
        self.tabWidget = QtWidgets.QTabWidget(self.frameDadosCliente)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 541, 461))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Cliente = QtWidgets.QWidget()
        self.tab_Cliente.setObjectName("tab_Cliente")
        self.bt_cancelar = QtWidgets.QToolButton(self.tab_Cliente)
        self.bt_cancelar.setGeometry(QtCore.QRect(110, 380, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_cancelar.setFont(font)
        self.bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelar.setStyleSheet("")
        self.bt_cancelar.setIcon(icon6)
        self.bt_cancelar.setIconSize(QtCore.QSize(48, 48))
        self.bt_cancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.bt_avancar = QtWidgets.QToolButton(self.tab_Cliente)
        self.bt_avancar.setGeometry(QtCore.QRect(320, 380, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_avancar.setFont(font)
        self.bt_avancar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_avancar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bt_avancar.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/iconSetaDireita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_avancar.setIcon(icon7)
        self.bt_avancar.setIconSize(QtCore.QSize(48, 48))
        self.bt_avancar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_avancar.setObjectName("bt_avancar")
        self.frameTab1 = QtWidgets.QFrame(self.tab_Cliente)
        self.frameTab1.setGeometry(QtCore.QRect(10, 10, 521, 361))
        self.frameTab1.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.frameTab1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTab1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTab1.setObjectName("frameTab1")
        self.txt_email = QtWidgets.QLabel(self.frameTab1)
        self.txt_email.setGeometry(QtCore.QRect(10, 310, 61, 16))
        self.txt_email.setObjectName("txt_email")
        self.txt_cep = QtWidgets.QLabel(self.frameTab1)
        self.txt_cep.setGeometry(QtCore.QRect(10, 260, 51, 16))
        self.txt_cep.setObjectName("txt_cep")
        self.txt_telefones = QtWidgets.QLabel(self.frameTab1)
        self.txt_telefones.setGeometry(QtCore.QRect(190, 260, 61, 16))
        self.txt_telefones.setObjectName("txt_telefones")
        self.lb_ierg = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_ierg.setGeometry(QtCore.QRect(280, 130, 231, 20))
        self.lb_ierg.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_ierg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_ierg.setObjectName("lb_ierg")
        self.lb_email = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_email.setGeometry(QtCore.QRect(10, 330, 501, 20))
        self.lb_email.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_email.setObjectName("lb_email")
        self.lb_class = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_class.setGeometry(QtCore.QRect(460, 30, 51, 20))
        self.lb_class.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_class.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_class.setObjectName("lb_class")
        self.txt_razaoSocial = QtWidgets.QLabel(self.frameTab1)
        self.txt_razaoSocial.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.txt_razaoSocial.setObjectName("txt_razaoSocial")
        self.lb_cidade = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_cidade.setGeometry(QtCore.QRect(280, 230, 231, 20))
        self.lb_cidade.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_cidade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_cidade.setText("")
        self.lb_cidade.setObjectName("lb_cidade")
        self.lb_uf = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_uf.setGeometry(QtCore.QRect(120, 280, 51, 20))
        self.lb_uf.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_uf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_uf.setObjectName("lb_uf")
        self.txt_IERG = QtWidgets.QLabel(self.frameTab1)
        self.txt_IERG.setGeometry(QtCore.QRect(280, 110, 61, 16))
        self.txt_IERG.setObjectName("txt_IERG")
        self.txt_cidade = QtWidgets.QLabel(self.frameTab1)
        self.txt_cidade.setGeometry(QtCore.QRect(280, 210, 61, 16))
        self.txt_cidade.setObjectName("txt_cidade")
        self.lb_razaoSocial = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_razaoSocial.setGeometry(QtCore.QRect(10, 30, 431, 20))
        self.lb_razaoSocial.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_razaoSocial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_razaoSocial.setText("")
        self.lb_razaoSocial.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lb_razaoSocial.setObjectName("lb_razaoSocial")
        self.txt_numero = QtWidgets.QLabel(self.frameTab1)
        self.txt_numero.setGeometry(QtCore.QRect(460, 160, 51, 16))
        self.txt_numero.setObjectName("txt_numero")
        self.txt_endereco = QtWidgets.QLabel(self.frameTab1)
        self.txt_endereco.setGeometry(QtCore.QRect(10, 160, 61, 16))
        self.txt_endereco.setObjectName("txt_endereco")
        self.txt_CNPJCPF = QtWidgets.QLabel(self.frameTab1)
        self.txt_CNPJCPF.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.txt_CNPJCPF.setObjectName("txt_CNPJCPF")
        self.txt_class = QtWidgets.QLabel(self.frameTab1)
        self.txt_class.setGeometry(QtCore.QRect(460, 10, 41, 16))
        self.txt_class.setObjectName("txt_class")
        self.txt_bairro = QtWidgets.QLabel(self.frameTab1)
        self.txt_bairro.setGeometry(QtCore.QRect(10, 210, 61, 16))
        self.txt_bairro.setObjectName("txt_bairro")
        self.txt_nomeFantasia = QtWidgets.QLabel(self.frameTab1)
        self.txt_nomeFantasia.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.txt_nomeFantasia.setObjectName("txt_nomeFantasia")
        self.lb_cnpjcpf = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_cnpjcpf.setGeometry(QtCore.QRect(10, 130, 251, 20))
        self.lb_cnpjcpf.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_cnpjcpf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_cnpjcpf.setObjectName("lb_cnpjcpf")
        self.txt_UF = QtWidgets.QLabel(self.frameTab1)
        self.txt_UF.setGeometry(QtCore.QRect(120, 260, 41, 16))
        self.txt_UF.setObjectName("txt_UF")
        self.lb_telefone = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_telefone.setGeometry(QtCore.QRect(190, 280, 321, 20))
        self.lb_telefone.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_telefone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_telefone.setText("")
        self.lb_telefone.setObjectName("lb_telefone")
        self.lb_endereco = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_endereco.setGeometry(QtCore.QRect(10, 180, 431, 20))
        self.lb_endereco.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_endereco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_endereco.setObjectName("lb_endereco")
        self.lb_numero = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_numero.setGeometry(QtCore.QRect(460, 180, 51, 20))
        self.lb_numero.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_numero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_numero.setObjectName("lb_numero")
        self.lb_cep = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_cep.setGeometry(QtCore.QRect(10, 280, 91, 20))
        self.lb_cep.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_cep.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_cep.setText("")
        self.lb_cep.setObjectName("lb_cep")
        self.lb_bairro = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_bairro.setGeometry(QtCore.QRect(10, 230, 251, 20))
        self.lb_bairro.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_bairro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_bairro.setObjectName("lb_bairro")
        self.lb_nomeFantasia = QtWidgets.QLineEdit(self.frameTab1)
        self.lb_nomeFantasia.setGeometry(QtCore.QRect(10, 80, 501, 20))
        self.lb_nomeFantasia.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_nomeFantasia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_nomeFantasia.setObjectName("lb_nomeFantasia")
        self.tabWidget.addTab(self.tab_Cliente, "")
        self.tab_dadosAdicionais = QtWidgets.QWidget()
        self.tab_dadosAdicionais.setObjectName("tab_dadosAdicionais")
        self.bt_confirmar = QtWidgets.QToolButton(self.tab_dadosAdicionais)
        self.bt_confirmar.setGeometry(QtCore.QRect(320, 380, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_confirmar.setFont(font)
        self.bt_confirmar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_confirmar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_confirmar.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/iconConfirmar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_confirmar.setIcon(icon8)
        self.bt_confirmar.setIconSize(QtCore.QSize(40, 48))
        self.bt_confirmar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_confirmar.setObjectName("bt_confirmar")
        self.bt_retornar = QtWidgets.QToolButton(self.tab_dadosAdicionais)
        self.bt_retornar.setGeometry(QtCore.QRect(110, 380, 121, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_retornar.setFont(font)
        self.bt_retornar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_retornar.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/iconSetaEsquerda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_retornar.setIcon(icon9)
        self.bt_retornar.setIconSize(QtCore.QSize(48, 48))
        self.bt_retornar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_retornar.setObjectName("bt_retornar")
        self.frameTab2 = QtWidgets.QFrame(self.tab_dadosAdicionais)
        self.frameTab2.setGeometry(QtCore.QRect(10, 10, 521, 351))
        self.frameTab2.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.frameTab2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTab2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTab2.setObjectName("frameTab2")
        self.lb_prazo = QtWidgets.QLineEdit(self.frameTab2)
        self.lb_prazo.setGeometry(QtCore.QRect(10, 320, 291, 20))
        self.lb_prazo.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lb_prazo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_prazo.setInputMask("")
        self.lb_prazo.setMaxLength(15)
        self.lb_prazo.setFrame(True)
        self.lb_prazo.setObjectName("lb_prazo")
        self.txt_CNPJCPF_2 = QtWidgets.QLabel(self.frameTab2)
        self.txt_CNPJCPF_2.setGeometry(QtCore.QRect(10, 290, 61, 16))
        self.txt_CNPJCPF_2.setObjectName("txt_CNPJCPF_2")
        self.txt_observacao = QtWidgets.QLabel(self.frameTab2)
        self.txt_observacao.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.txt_observacao.setObjectName("txt_observacao")
        self.lb_observacao = QtWidgets.QTextEdit(self.frameTab2)
        self.lb_observacao.setGeometry(QtCore.QRect(10, 30, 501, 241))
        self.lb_observacao.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lb_observacao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_observacao.setObjectName("lb_observacao")
        self.tabWidget.addTab(self.tab_dadosAdicionais, "")
        self.bt_inutilizado1 = QtWidgets.QToolButton(formCliente)
        self.bt_inutilizado1.setGeometry(QtCore.QRect(360, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_inutilizado1.setFont(font)
        self.bt_inutilizado1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_inutilizado1.setStyleSheet("")
        self.bt_inutilizado1.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../formNotaFiscal_completa/Icons/Icon_Interrogacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_inutilizado1.setIcon(icon10)
        self.bt_inutilizado1.setIconSize(QtCore.QSize(80, 80))
        self.bt_inutilizado1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_inutilizado1.setObjectName("bt_inutilizado1")
        self.bt_inutilizado2 = QtWidgets.QToolButton(formCliente)
        self.bt_inutilizado2.setGeometry(QtCore.QRect(450, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_inutilizado2.setFont(font)
        self.bt_inutilizado2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_inutilizado2.setStyleSheet("")
        self.bt_inutilizado2.setText("")
        self.bt_inutilizado2.setIcon(icon10)
        self.bt_inutilizado2.setIconSize(QtCore.QSize(80, 80))
        self.bt_inutilizado2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_inutilizado2.setObjectName("bt_inutilizado2")
        self.bt_inutilizado3 = QtWidgets.QToolButton(formCliente)
        self.bt_inutilizado3.setGeometry(QtCore.QRect(540, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_inutilizado3.setFont(font)
        self.bt_inutilizado3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_inutilizado3.setStyleSheet("")
        self.bt_inutilizado3.setText("")
        self.bt_inutilizado3.setIcon(icon10)
        self.bt_inutilizado3.setIconSize(QtCore.QSize(80, 80))
        self.bt_inutilizado3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_inutilizado3.setObjectName("bt_inutilizado3")
        self.bt_inutilizado4 = QtWidgets.QToolButton(formCliente)
        self.bt_inutilizado4.setGeometry(QtCore.QRect(630, 0, 91, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_inutilizado4.setFont(font)
        self.bt_inutilizado4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_inutilizado4.setStyleSheet("")
        self.bt_inutilizado4.setText("")
        self.bt_inutilizado4.setIcon(icon10)
        self.bt_inutilizado4.setIconSize(QtCore.QSize(80, 80))
        self.bt_inutilizado4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_inutilizado4.setObjectName("bt_inutilizado4")

        self.retranslateUi(formCliente)
        self.tabWidget.setCurrentIndex(0)
        self.bt_cancelar.clicked.connect(self.frameDadosCliente.hide) # type: ignore
        self.bt_incluir.clicked.connect(self.frameDadosCliente.show) # type: ignore
        self.bt_confirmar.clicked.connect(self.frameDadosCliente.hide) # type: ignore
        self.bt_consultar.clicked.connect(self.frameDadosCliente.show) # type: ignore
        self.bt_sair.clicked.connect(formCliente.close) # type: ignore
        self.bt_alterar.clicked.connect(self.frameDadosCliente.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(formCliente)
        formCliente.setTabOrder(self.lb_razaoSocial, self.lb_class)
        formCliente.setTabOrder(self.lb_class, self.lb_nomeFantasia)
        formCliente.setTabOrder(self.lb_nomeFantasia, self.lb_cnpjcpf)
        formCliente.setTabOrder(self.lb_cnpjcpf, self.lb_ierg)
        formCliente.setTabOrder(self.lb_ierg, self.lb_endereco)
        formCliente.setTabOrder(self.lb_endereco, self.lb_numero)
        formCliente.setTabOrder(self.lb_numero, self.lb_bairro)
        formCliente.setTabOrder(self.lb_bairro, self.lb_cidade)
        formCliente.setTabOrder(self.lb_cidade, self.lb_cep)
        formCliente.setTabOrder(self.lb_cep, self.lb_uf)
        formCliente.setTabOrder(self.lb_uf, self.lb_telefone)
        formCliente.setTabOrder(self.lb_telefone, self.lb_email)

    def retranslateUi(self, formCliente):
        _translate = QtCore.QCoreApplication.translate
        formCliente.setWindowTitle(_translate("formCliente", "Cliente"))
        self.txt_nomeCliente.setText(_translate("formCliente", "Nome Cliente:"))
        self.bt_sair.setText(_translate("formCliente", "Sair"))
        self.bt_incluir.setText(_translate("formCliente", "Incluir"))
        item = self.tb_cliente.horizontalHeaderItem(1)
        item.setText(_translate("formCliente", "Razão Social"))
        item = self.tb_cliente.horizontalHeaderItem(2)
        item.setText(_translate("formCliente", "Nome Fantasia"))
        item = self.tb_cliente.horizontalHeaderItem(3)
        item.setText(_translate("formCliente", "Classificação"))
        item = self.tb_cliente.horizontalHeaderItem(4)
        item.setText(_translate("formCliente", "CNPJ/CPF"))
        item = self.tb_cliente.horizontalHeaderItem(5)
        item.setText(_translate("formCliente", "I.E/RG"))
        item = self.tb_cliente.horizontalHeaderItem(6)
        item.setText(_translate("formCliente", "Endereço"))
        item = self.tb_cliente.horizontalHeaderItem(7)
        item.setText(_translate("formCliente", "Número"))
        item = self.tb_cliente.horizontalHeaderItem(8)
        item.setText(_translate("formCliente", "Bairro"))
        item = self.tb_cliente.horizontalHeaderItem(9)
        item.setText(_translate("formCliente", "CEP"))
        item = self.tb_cliente.horizontalHeaderItem(10)
        item.setText(_translate("formCliente", "Cidade"))
        item = self.tb_cliente.horizontalHeaderItem(11)
        item.setText(_translate("formCliente", "Estado"))
        item = self.tb_cliente.horizontalHeaderItem(12)
        item.setText(_translate("formCliente", "Telefone"))
        item = self.tb_cliente.horizontalHeaderItem(13)
        item.setText(_translate("formCliente", "email"))
        item = self.tb_cliente.horizontalHeaderItem(14)
        item.setText(_translate("formCliente", "Observação"))
        item = self.tb_cliente.horizontalHeaderItem(15)
        item.setText(_translate("formCliente", "Prazo"))
        item = self.tb_cliente.horizontalHeaderItem(16)
        item.setText(_translate("formCliente", "Usuário"))
        item = self.tb_cliente.horizontalHeaderItem(17)
        item.setText(_translate("formCliente", "Auditoria"))
        self.bt_alterar.setText(_translate("formCliente", "Alterar"))
        self.bt_consultar.setText(_translate("formCliente", "Consultar"))
        self.bt_excluir.setText(_translate("formCliente", "Excluir"))
        self.bt_cancelar.setText(_translate("formCliente", "Cancelar"))
        self.bt_avancar.setText(_translate("formCliente", "Avançar"))
        self.txt_email.setText(_translate("formCliente", "E-mail"))
        self.txt_cep.setText(_translate("formCliente", "CEP"))
        self.txt_telefones.setText(_translate("formCliente", "Telefones:"))
        self.txt_razaoSocial.setText(_translate("formCliente", "Razão Social"))
        self.txt_IERG.setText(_translate("formCliente", "I.E/RG"))
        self.txt_cidade.setText(_translate("formCliente", "Cidade"))
        self.txt_numero.setText(_translate("formCliente", "Número"))
        self.txt_endereco.setText(_translate("formCliente", "Endereço"))
        self.txt_CNPJCPF.setText(_translate("formCliente", "CNPJ/CPF"))
        self.txt_class.setText(_translate("formCliente", "Class"))
        self.txt_bairro.setText(_translate("formCliente", "Bairro"))
        self.txt_nomeFantasia.setText(_translate("formCliente", "Nome Fantasia"))
        self.txt_UF.setText(_translate("formCliente", "UF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Cliente), _translate("formCliente", "Cliente"))
        self.bt_confirmar.setText(_translate("formCliente", "Confirmar"))
        self.bt_retornar.setText(_translate("formCliente", "Retornar"))
        self.txt_CNPJCPF_2.setText(_translate("formCliente", "Prazo:"))
        self.txt_observacao.setText(_translate("formCliente", "Observação"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dadosAdicionais), _translate("formCliente", "Dados adicionais"))

        self.frameDadosCliente.hide()

        self.lb_observacao.setFocus() #Todo: faz funciona o texto da area grande
        

        #TODO: Botões sair do sistema

        self.bt_sair.clicked.connect(formCliente.close) #Todo: sai da tela.

        self.bt_excluir.clicked.connect(self.excluirCliente) #Todo: exclui o cliente.

        self.bt_pesquisarGeral.clicked.connect(self.consultarGeral) #Todo: pesquisa Geral

        self.bt_pesquisar.clicked.connect(self.consultarNomes) #Todo: consulta por nome

        self.bt_retornar.clicked.connect(self.retornarPagTab) #Todo: Retorna a pagina 0

        self.bt_avancar.clicked.connect(self.avancaPagTab) #Todo: vai para a página 1

        self.bt_confirmar.clicked.connect(self.cadastrarCliente) #Todo: Cadastra cliente no banco de dados.


    #TODO: funções da tela cliente.
    def sairTelaCliente(self):
        sys.exit()

    def retornarPagTab(self):
        self.tabWidget.setCurrentIndex(0)

    def avancaPagTab(self):
        self.tabWidget.setCurrentIndex(1)

    def cadastrarCliente(self):

        #Todo: seta labels das variaveis.
        razaoSocial = self.lb_razaoSocial.text() #1
        nomeFantasia = self.lb_nomeFantasia.text() #2
        classificacao = self.lb_class.text() #3
        cnpjcpf = self.lb_cnpjcpf.text() #4
        ierg = self.lb_ierg.text() #5
        endereco = self.lb_endereco.text() #6
        numero = self.lb_numero.text() #7
        bairro = self.lb_bairro.text() #8
        cidade = self.lb_cidade.text() #9
        cep = self.lb_cep.text() #10
        estado = self.lb_uf.text() #11
        telefone = self.lb_telefone.text() #12
        email = self.lb_email.text() #13
        observacao = self.lb_observacao.toPlainText() #14
        prazo = self.lb_prazo.text() #15
        usuarioCadastro = 1 #16
        dataHoje = datetime.today().strftime('%H:%M:%S - %d-%m-%Y')
        serialUniqPC = subprocess.check_output('wmic bios get serialnumber').decode("utf-8")
        auditoria ="Hora Exata:" + str(dataHoje) + ' Máquina: ' + str(serialUniqPC[36:49] + ' Usuário: ' + str(usuarioCadastro)) #17

        print(dataHoje)
        print('cadastrado com sucesso')

        #todo: testando as captações

        """print(razaoSocial)
        print(nomeFantasia)
        print(classificacao)
        print(cnpjcpf)
        print(ierg)
        print(endereco)
        print(numero)
        print(bairro)
        print(cidade)
        print(cep)
        print(estado)
        print(telefone)
        print(email)
        print(observacao)
        print(prazo)
        print(auditoria)"""

        #Todo: fazer uma checagem se esta tudo vazio com a finalidade de não haver erros

        if razaoSocial == '':
            razaoaSocial = None
        if nomeFantasia == '':
            nomeFantasia = None
        if classificacao == '':
            classificacao = None
        if cnpjcpf == '':
            cnpjcpf = None
        if ierg =='':
            ierg = None
        if endereco == '':
            endereco = None
        if numero == '':
            numero = None
        if bairro == '':
            bairro = None
        if cidade == '':
            cidade = None
        if cep =='':
            cep = None
        if estado =='':
            estado = None
        if telefone == '':
            telefone = None
        if email == '':
            email = None
        if observacao == '':
            observacao = None
        if prazo == '':
            prazo = None

        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database

        )
            mycursor = mydb.cursor()
            sql = "INSERT INTO cliente (razaoSocial, nomeFantasia, classificacao, cnpjcpf, ierg, endereco, numero, bairro, cidade, cep,  estado, telefone, email, observacao, prazo, usuarioCadastro, auditoria) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            val = (razaoSocial, nomeFantasia, classificacao, cnpjcpf, ierg, endereco, numero, bairro, cidade, cep, estado, telefone, email, observacao, prazo, usuarioCadastro, auditoria)
            mycursor.execute(sql,val)
            #M commit o banco de dados
            mydb.commit()


            self.lb_razaoSocial.clear()
            self.lb_nomeFantasia.clear()
            self.lb_class.clear()
            self.lb_cnpjcpf.clear()
            self.lb_ierg.clear()
            self.lb_endereco.clear()
            self.lb_numero.clear()
            self.lb_bairro.clear()
            self.lb_cidade.clear()
            self.lb_cep.clear()
            self.lb_uf.clear()
            self.lb_telefone.clear()
            self.lb_email.clear()
            self.lb_observacao.clear()
            self.lb_prazo.clear()
            self.tabWidget.setCurrentIndex(0) #Todo: volta página 0

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setWindowTitle("Adição")
            msg.setText(f" Adicionado com sucesso!")
            msg.setStyleSheet("color: rgb(0, 170, 0)")
            msg.exec_()
            self.consultarGeral()






        except:
            print('')
            msg = QMessageBox()
            msg.setIcon(QMessageBox.critical)
            msg.setText("Erro SQL")
            msg.setInformativeText('Favor contactar o administrador do sistema!')
            msg.setWindowTitle('Erro')
            msg.exec_()

            mycursor.close()
            mydb.close()









    def excluirCliente(self):



        print('Excluindo cliente....')
        msg = QMessageBox()
        msg.setWindowTitle("Aviso")
        msg.setText("Deseja realmente Excluir os dados")
        msg.setStandardButtons(QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)
        ret = msg.exec()

        if ret == QMessageBox.StandardButton.Yes:
            linha = self.tb_cliente.currentRow()
            idClienteLinha = self.tb_cliente.item(linha,0).text()

            try:

                mydb = mysql.connector.connect(
                    host = host,
                    user = user,
                    password = password,
                    database = database

                )
                mycursor = mydb.cursor()
                sql = f"DELETE From cliente WHERE idCliente = '{idClienteLinha}'"
                mycursor.execute(sql)
                mydb.commit()
                print(mycursor.rowcount, "Excluído com sucesso")
                msg = QMessageBox()
                msg.setWindowTitle("Aviso")
                msg.setText(f"Cliente {idClienteLinha} excluido com sucesso")
                msg.exec_()
                self.consultarGeral()


            except:


                self.all_data = 0
                print('tente depois')
                msg = QMessageBox()
                msg.setWindowTitle("Aviso")
                msg.setText('Não foi possível fazer a exclusão')
                msg.exec_()









            msg.setStandardButtons(QMessageBox.StandardButton.Ok)
            ret = msg.exec()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Aviso")
            msg.setText("Cliente não excluido")
            msg.setStandardButtons(QMessageBox.StandardButton.Ok)
            ret = msg.exec()

        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database

            )
            mycursor = mydb.cursor()
            sql = "SELECT * FROM cliente"
            mycursor.execute(sql)
            myresult = mycursor.fetchall()

        except:
            self.all_data = 0
            msg = QMessageBox()
            msg.setIcon(QMessageBox.warning)
            msg.setText("Error")
            msg.setInformativeText("Não foi possível consultar a tabela!")
            msg.setWindowTitle("Error")
            msg.exec_()
            pass


    def consultarGeral(self):

        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database

            )
            mycursor = mydb.cursor()
            sql = "SELECT * FROM cliente"
            mycursor.execute(sql)
            myresult = mycursor.fetchall()

            df_cliente = pd.DataFrame(myresult, columns=['idCliente','razaoSocial','nomeFantasia','classificacao','cnpjcpf','ierg','endereco','numero','bairro','cep','cidade','estado','telefone','email','observacao','prazo','usuarioCadastro','auditoria'])
            self.all_data = df_cliente
            #Todo: Carrega o arquivo na Tabela cliente
            numRows = len(self.all_data.index)
            self.tb_cliente.setColumnCount(len(self.all_data.columns))
            self.tb_cliente.setRowCount(numRows)
            #self.tb_cliente.setHorizontalHeaderLabels(self.all_data.columns) #Setar o título e cabeçalho da tabela

            for i in range(numRows):
                for j in range(len(self.all_data.columns)):
                    self.tb_cliente.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))


            self.tb_cliente.resizeColumnsToContents()
            self.tb_cliente.resizeRowsToContents()



            mycursor.close()




        except:
            self.all_data = 0
            msg = QMessageBox()
            msg.setIcon(QMessageBox.warning)
            msg.setText("Error")
            msg.setInformativeText("Não foi possível consultar a tabela!")
            msg.setWindowTitle("Error")
            msg.exec_()
            pass


    def consultarNomes(self):
        print('Consultar por nome')
        procurarNome = self.lb_nomeCliente.text()

        try:
            mydb = mysql.connector.connect(
                host = host,
                user = user,
                password = password,
                database = database

            )
            mycursor = mydb.cursor()
            sql = f"SELECT * FROM cliente WHERE razaoSocial LIKE '{procurarNome}%' ORDER BY razaoSocial"
            mycursor.execute(sql)
            myresult = mycursor.fetchall()
            print(myresult)
            df_cliente = pd.DataFrame(myresult, columns=['idCliente','razaoSocial','nomeFantasia','classificacao','cnpjcpf','ierg','endereco','numero','bairro','cep','cidade','estado','telefone','email','observacao','prazo','usuarioCadastro','auditoria'])
            self.all_data = df_cliente
            #Todo: Carrega o arquivo na Tabela cliente
            numRows = len(self.all_data.index)
            self.tb_cliente.setColumnCount(len(self.all_data.columns))
            self.tb_cliente.setRowCount(numRows)
            #self.tb_cliente.setHorizontalHeaderLabels(self.all_data.columns) #Setar o título e cabeçalho da tabela

            for i in range(numRows):
                for j in range(len(self.all_data.columns)):
                    self.tb_cliente.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))


            self.tb_cliente.resizeColumnsToContents()
            self.tb_cliente.resizeRowsToContents()

            mycursor.close()

        except:
            self.all_data = 0
            msg = QMessageBox()
            msg.setIcon(QMessageBox.warning)
            msg.setText("Error")
            msg.setInformativeText("Não foi possível consultar a tabela!")
            msg.setWindowTitle("Error")
            msg.exec()
            pass




    def avancarTela(self):
        print('')
        self.frameTab2.show()
        




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formCliente = QtWidgets.QWidget()
    ui = Ui_formCliente()
    ui.setupUi(formCliente)
    formCliente.show()
    sys.exit(app.exec_())
